name: release

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        django:
        - '3.2'
        - '4.0'
        - '4.1'
        - '4.2'
        - '5.0'
        - 'main'
        exclude:
          - python-version: '3.7'
            django: '4.0'
          - python-version: '3.7'
            django: '4.1'
          - python-version: '3.7'
            django: '4.2'
          - python-version: '3.7'
            django: '5.0'
          - python-version: '3.7'
            django: 'main'
          - python-version: '3.8'
            django: '5.0'
          - python-version: '3.9'
            django: '5.0'
          - python-version: '3.11'
            django: '3.2'
          - python-version: '3.11'
            django: '4.0'
          - python-version: '3.12'
            django: '3.2'
          - python-version: '3.12'
            django: '4.0'
          - python-version: '3.12'
            django: '4.1'
          - python-version: '3.12'
            django: '4.2'

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/test
      with:
        python-version: ${{ matrix.python-version }}
        django-version: ${{ matrix.django }}

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: build
      run: ./run.sh build

    - name: check
      run: ./run.sh check

    - name: release
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_DEPLOY_TOKEN }}
